# ESTO ES UN COMENTARIO
# Todo lo que está a la derecha de # es solo para nosotros

version: 0.3.5 # NO TOCAR

# HODL username
username: "uxjossie" # < TU_USUARIO@hodl.ar

# NOSTR Settings
nostr: # Sin el # adelante
  npub: "npub1vm67q97d0fh4gqkwa2edrvz83q5u4hfd0cjyem5ynx3enzsd5nuqkgj7ql" # Entre comillas dobles

# Configuración Global
html:
# title: Este valor no funciona porque esta comentado
  title: Links | Jossie Anschutz # Este es el Título que aparece en la pestaña de navegador

# Colores de plantilla
theme:
  background_color: "#f9fafb"
  # cover_color: "#ff7070"

# Configuración Central
main:
  title: "Jossie Anschutz" # Aca podes poner tu nombre o el de tu producto

# Lista de bloques
blocks:
  # Estos bloques los podes editar cambiando SOLO el texto que está en blanco
  # Sacale 

  - title: Instagram
    icon: instagram
    url: https://www.instagram.com/josieanschutz/

  - title: Twitter
    icon: twitter
    url: https://twitter.com/uxjossie
    
  - title: LinkedIn # Este es el nombre del botón
    icon: linkedin # Este es el nombre del icono (si queres añadir una red social nueva, prestá atencion que es todo con minúscula)
    url: https://www.linkedin.com/in/josefina-anschutz/ # Link a donde redireccionará al hacer click

  - title: Github
    icon: github
    url: https://github.com/JossieAns87

  - title: Sitio Web
    icon: url
    url: https://www.notion.so/Hola-I-am-Jossie-UX-Writer-with-swag-d44001431330446ab77ab53f79f694df

  - title: Telegram
    icon: telegram
    url: https://t.me/uxjossie
    
# Guardá el archivo haciendo click en Commit Changes, abajo
# Volvé a las instrucciones
